FROM ghcr.io/ggml-org/llama.cpp:server-cuda

ENV LLAMA_ARG_MODEL="/root/models/Qwen3.5-27B-heretic.Q6_K.gguf"
ENV LLAMA_ARG_MMPROJ="/root/models/Qwen3.5-27B-heretic.mmproj-f16.gguf"
ENV LLAMA_ARG_CTX_SIZE=131072
ENV LLAMA_ARG_N_GPU_LAYERS=99
ENV LLAMA_ARG_FLASH_ATTN=on
ENV LLAMA_ARG_HOST=0.0.0.0
ENV LLAMA_ARG_PORT=8080
ENV LLAMA_ARG_N_PARALLEL=4
ENV LLAMA_ARG_THINK_BUDGET=0

EXPOSE 8080
